services:
  gitea:
    image: docker.gitea.com/gitea:1.25.1
    container_name: gitea
    environment:
      USER_UID: 1000
      USER_GID: 1000
    restart: always
    network_mode: host
    volumes:
      - ./.data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s

  runner:
    image: docker.io/gitea/act_runner:nightly
    container_name: runner
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "http://localhost:3000"
      GITEA_RUNNER_REGISTRATION_TOKEN: ${GITEA_RUNNER_REGISTRATION_TOKEN}
      GITEA_RUNNER_NAME: "runner"
    depends_on:
      gitea:
        condition: service_healthy
        restart: true
    network_mode: host
    volumes:
      - ./configs/runner.yaml:/config.yaml
      - ./.data/runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
